name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo
      - name: update Node.js
        run : |
              sudo apt update
              sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
              curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
              sudo apt -y install nodejs
              npm install hexo-deployer-git --save
      - name: Use Node.js 12.22.12
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.12
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "462god@gmail.com"
          git config --global user.name "MogamiKawa"
          npm install hexo-cli -g
          npm install
      - name: Hexo deploy
        run: |
          hexo clean
          hexo d